#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用于连接本地数据库测试是否能正确运行
    url: mpw:2lcQAYsfwxTCA01l9k60E/6Fj6eAuX0dVmEa2Mq7OVoBkpTTrVfQr2WJx2wA9Z/svalzwEapYrUNaDjYLdAuBMcxqcOyLHak5/auN3oJTeWJpEtq66kjG5EAilfuxiUInUr8eHictRXX76vZP8O01cVbkl+8yqqOQ9PVhZ5309M=
    username: mpw:h3gmHVCJFcFPfeZ7DReYpw==
    password: mpw:HCQusJ+fyXYmL3k8haYXfQ==
    hikari:
      max-lifetime: 1800000  #连接的最大生命周期，表示一个连接在被关闭之前的最长使用时间。设置为30分钟（1800000毫秒）
  data:
    redis:
      port: 6379
      host: mpw:3gpw306DSQiUTJbJPcW76Q==
      password: mpw:HCQusJ+fyXYmL3k8haYXfQ==
      database: 0
      connect-timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池中的最小空闲连接
          min-idle: 0